// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    //apiKey: 'AIzaSyAl7aJ3ZwiYxe7QFQiUi1dsx1DlcaBUKg0',
    apiKey: dotenv.env['WEB_API_KEY'].toString(),
    appId: dotenv.env['WEB_APP_ID'].toString(),
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'].toString(),
    projectId: dotenv.env['FIREBASE_PROJECT_ID'].toString(),
    authDomain: dotenv.env['WEB_AUTH_DOMAIN'].toString(),
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'].toString(),
    measurementId: dotenv.env['WEB_MEASUREMENT_ID'].toString(),
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROID_API_KEY'].toString(),
    appId: dotenv.env['ANDROID_APP_ID'].toString(),
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'].toString(),
    projectId: dotenv.env['FIREBASE_PROJECT_ID'].toString(),
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'].toString(),
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS_API_KEY'].toString(),
    appId: dotenv.env['IOS_APP_ID'].toString(),
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'].toString(),
    projectId: dotenv.env['FIREBASE_PROJECT_ID'].toString(),
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'].toString(),
    androidClientId: dotenv.env['ANDROID_CLIENT_ID'].toString(),
    iosClientId: dotenv.env['IOS_CLIENT_ID'].toString(),
    iosBundleId: dotenv.env['IOS_BUNDLE_ID'].toString(),
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['MACOS_API_KEY'].toString(),
    appId: dotenv.env['MACOS_APP_ID'].toString(),
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'].toString(),
    projectId: dotenv.env['FIREBASE_PROJECT_ID'].toString(),
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'].toString(),
    androidClientId: dotenv.env['ANDROID_CLIENT_ID'].toString(),
    iosClientId: dotenv.env['MACOS_CLIENT_ID'].toString(),
    iosBundleId: dotenv.env['MACOS_BUNDLE_ID'].toString(),
  );
}
