// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl7aJ3ZwiYxe7QFQiUi1dsx1DlcaBUKg0',
    appId: '1:292158676694:web:707c591d3460a2808ab377',
    messagingSenderId: '292158676694',
    projectId: 'sprint-project-ab169',
    authDomain: 'sprint-project-ab169.firebaseapp.com',
    storageBucket: 'sprint-project-ab169.appspot.com',
    measurementId: 'G-6NMRV3GHCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHkFwDkwgwk5lXav31UwXjV2G4X0StxG0',
    appId: '1:292158676694:android:9ac8abb4798755ff8ab377',
    messagingSenderId: '292158676694',
    projectId: 'sprint-project-ab169',
    storageBucket: 'sprint-project-ab169.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz6VhiiZNwJg8S9FlWZZj2uZj8Fj4Swyo',
    appId: '1:292158676694:ios:50652d810391e2cf8ab377',
    messagingSenderId: '292158676694',
    projectId: 'sprint-project-ab169',
    storageBucket: 'sprint-project-ab169.appspot.com',
    androidClientId: '292158676694-iftep6ql676rtq6snskb2s9udlkt6t5m.apps.googleusercontent.com',
    iosClientId: '292158676694-d12ula7o0u07l804oi7cs7gvvrq76o1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.sprint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz6VhiiZNwJg8S9FlWZZj2uZj8Fj4Swyo',
    appId: '1:292158676694:ios:9f86014e2eaa8e838ab377',
    messagingSenderId: '292158676694',
    projectId: 'sprint-project-ab169',
    storageBucket: 'sprint-project-ab169.appspot.com',
    androidClientId: '292158676694-iftep6ql676rtq6snskb2s9udlkt6t5m.apps.googleusercontent.com',
    iosClientId: '292158676694-gr1u5mnevdbl3jlfp1dhhfsarnpv1v8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.sprint.RunnerTests',
  );
}