name: flutteractionweb
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
     - run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
     - run: flutter build linux
