ame: Flutter

on:
  push:
    branches: [main, v*]
  pull_request:
    branches: [main, v*]
  schedule:
    # https://crontab.guru/#40_10_*_*_*
    - cron: '40 10 * * *'
  workflow_dispatch:
  
jobs:
  test-stable:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version:
          - latest
          - 3.3.0
          - 3.0.0
          - 2.10.5
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          channel: stable
          version: ${{ matrix.version }}

      - name: Dart version
        run: dart --version
      - name: Flutter version
        run: flutter --version
      - name: Flutter doctor
        run: flutter doctor

      - name: Run hello world
        run: |
          echo "main() { print('hello world'); }" > hello.dart
          dart hello.dart
  test-beta:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version:
          - latest
          - 3.3.0-0.0.pre
          - 3.1.0
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          channel: beta
          version: ${{ matrix.version }}

      - name: Dart version
        run: dart --version
      - name: Flutter version
        run: flutter --version
      - name: Flutter doctor
        run: flutter doctor

      - name: Run hello world
        run: |
          echo "main() { print('hello world'); }" > hello.dart
          dart hello.dart
